config/routes.rb
GameOfLife::Application.routes.draw do

  root 'static_pages#home'

  match '/play', to: 'static_pages#play', via: 'get'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
  end

  def play
  	@row = 15
  	@col = 30
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>Conway's Game Of Life</title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
    <link href='http://fonts.googleapis.com/css?family=Varela+Round' rel='stylesheet' type='text/css'>
  </head>

  <body class='wrapper'>
    <div class='small-12 columns'>
      <%= yield %>
      <%= javascript_include_tag "application" %>
    </div>

  </body>
</html>

app/views/static_pages/home.html.erb
<div class='title-div small-10 small-centered columns'>
  <div class='child'>
    <h1>Conway's</h1>
    <h2><%= link_to 'Game of Life', play_path %></h2>
  </div>
</div>

app/views/static_pages/play.html.erb
<div class='grid-div'>
  <table id='play_grid'>
    <input class = 'row_val' type='hidden' value= '<%=@row%>'>
    <input class = 'col_val' type='hidden' value= '<%=@col%>'>
    <% @row.times do |y| %>
    <tr class= 'row_<%= y.to_s %>'>
      <% @col.times do |x| %>
        <td class= 'col_<%= x.to_s %> clickable'>
          <input class = 'x' type='hidden' value= '<%=x%>'>
          <input class = 'y' type='hidden' value= '<%=y%>'>
        </td>

      <% end %>
    </tr>
    <% end %>
  </table>
  <div class='row'>
    <div class='small-3 columns'>
      <!-- <button>pattern 1</button> -->
    </div>
  </div>
  <div class='row'>
    <div class='generation-and-button'>
      <h3 id='gen_tag'>Generations: 0</h3>
      <button id="start_life_btn">Begin Time</button>
      <button id="end_life_btn">End Time</button>
    </div>
    <div class='rules'>

        <h2>Rules Of Life</h2>
        <ul class='rules-list'>
          <li>A cell is 'living' if it is colored in. A cell is 'dead' if it is blank. You can bring to life cells by clicking in them.</li>
          <li>Any live cell with fewer than two live neighbours dies, as if caused by under-population.</li>
          <li>Any live cell with two or three live neighbours lives on to the next generation.</li>
          <li>Any live cell with more than three live neighbours dies, as if by overcrowding.</li>
          <li>Any dead cell with exactly three live neighbours becomes a live cell, as if by reproduction.</li>
        </ul>
        <p>More info about Conway's game can be found <a href="http://en.wikipedia.org/wiki/Conway%27s_Game_of_Life">here</a>. The app was created by <a href="http://razajafri.info">Raza Jafri</a></p>
      </div>
  </div>
</div>